#!/usr/bin/env python
#
# Copyright (c) J. A. Zanardo Jr. <zanardo@gmail.com>
# Please refer to COPYING for license details
# Please refer to README for general instructions
#

"""

Filesystem usage collector.

Usage:

    rrd-df RRDHOST:RRDPORT RRDNAME MOUNT-POINT

suggested data configuration:

    --step=60
    DS:used:GAUGE:120:0:100
    RRA:AVERAGE:0.5:1:120
    RRA:AVERAGE:0.5:5:288
    RRA:AVERAGE:0.5:30:336
    RRA:AVERAGE:0.5:120:360
    RRA:AVERAGE:0.5:1440:360

Suggested graph configuration:

    --title=localhost: Used filesystem space
    --lower-limit=0
    --upper-limit=100
    DEF:root=localhost-df-root.rrd:used:AVERAGE
    DEF:home=localhost-df-home.rrd:used:AVERAGE
    LINE2:root#FF0000:/
    GPRINT:root:LAST:    Now\:%3.0lf%% used\\n
    LINE2:home#0000FF:/home
    GPRINT:home:LAST:Now\:%3.0lf%% used

"""

import socket, sys, re, os

rrdhost, rrdport = sys.argv[1].split(':')
rrdname = sys.argv[2]
mountpoint = sys.argv[3]

stat = os.statvfs(mountpoint)
used = 100.0 - ( float(stat.f_bfree) / float(stat.f_blocks) * 100.0 )

# Sending data via UDP
msg = "%s N:%d" % ( rrdname, used )
socket.socket(socket.AF_INET, socket.SOCK_DGRAM).sendto(msg, (rrdhost, int(rrdport)))
sys.stderr.write(msg + '\n')
