#!/usr/bin/env python
#
# Copyright (c) J. A. Zanardo Jr. <zanardo@gmail.com>
# Please refer to COPYING for license details
# Please refer to README for general instructions
#

"""

Number of active/sleeping processes collector.

Usage:

    rrd-nproc RRDHOST:RRDPORT RRDNAME

Suggested data configuration:

    --step=60
    DS:running:GAUGE:120:0:U
    DS:sleeping:GAUGE:120:0:U
    RRA:AVERAGE:0.5:1:120
    RRA:AVERAGE:0.5:5:288
    RRA:AVERAGE:0.5:30:336
    RRA:AVERAGE:0.5:120:360
    RRA:AVERAGE:0.5:1440:360

Suggested graph configuration:

    -E
    --title=localhost: Number of processes
    DEF:running=localhost-nproc.rrd:running:AVERAGE
    DEF:sleeping=localhost-nproc.rrd:sleeping:AVERAGE
    AREA:running#0000FF:Running
    STACK:sleeping#32CD32:Sleeping

"""

import socket, sys, re

rrdhost, rrdport = sys.argv[1].split(':')
rrdname = sys.argv[2]

fp = open('/proc/loadavg')
line = fp.readline()
fp.close()
nr, ns = re.match('^[0-9\.]+ [0-9\.]+ [0-9\.]+ (\d+)\/(\d+) ', line).groups()

# Sending data via UDP
msg = "%s N:%s:%s" % ( rrdname, nr, ns )
socket.socket(socket.AF_INET, socket.SOCK_DGRAM).sendto(msg, (rrdhost, int(rrdport)))
sys.stderr.write(msg + '\n')
