#!/usr/bin/env python
#
# Copyright (c) J. A. Zanardo Jr. <zanardo@gmail.com>
# Please refer to COPYING for license details
# Please refer to README for general instructions
#

"""

Load Average collector.

Usage:

    rrd-loadavg RRDHOST:RRDPORT RRDNAME

Suggested data configuration:

    --step=60
    DS:1m:GAUGE:120:0:U
    DS:5m:GAUGE:120:0:U
    DS:15m:GAUGE:120:0:U
    RRA:AVERAGE:0.5:1:120
    RRA:AVERAGE:0.5:5:288
    RRA:AVERAGE:0.5:30:336
    RRA:AVERAGE:0.5:120:360
    RRA:AVERAGE:0.5:1440:360

Suggested graph configuration:

    --title=localhost: Load Average
    DEF:1m=localhost-loadavg.rrd:1m:AVERAGE
    DEF:5m=localhost-loadavg.rrd:5m:AVERAGE
    DEF:15m=localhost-loadavg.rrd:15m:AVERAGE
    LINE1:1m#0000FF:1 minute average
    LINE1:5m#00FF00:5 minutes average
    LINE1:15m#FF0000:15 minutes average

"""

import socket, sys, re

rrdhost, rrdport = sys.argv[1].split(':')
rrdname = sys.argv[2]

fp = open('/proc/loadavg')
line = fp.readline()
fp.close()
la1m, la5m, la15m = re.split(' *', line)[0:3]

# Sending data via UDP
msg = "%s N:%s:%s:%s" % ( rrdname, la1m, la5m, la15m ) 
socket.socket(socket.AF_INET, socket.SOCK_DGRAM).sendto(msg, (rrdhost, int(rrdport)))
sys.stderr.write(msg + '\n')
